# Generated by Django 3.0.7 on 2020-07-24 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('netID', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('major', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=50)),
                ('rescollege', models.CharField(max_length=50)),
                ('profile_picture', models.ImageField(default='default_profile_picture.png', upload_to='images/')),
                ('days', models.CharField(max_length=300)),
                ('duration', models.CharField(max_length=50)),
                ('workout_type', models.CharField(max_length=50)),
                ('time_zone', models.CharField(max_length=50)),
                ('group_size', models.IntegerField(default=2)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
