# Generated by Django 3.0.7 on 2021-01-07 18:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('buddyrequest', '0003_auto_20210107_0331'),
    ]

    operations = [
        migrations.AddField(
            model_name='buddyrequest',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
