# Generated by Django 3.0.7 on 2021-01-27 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddyrequest', '0008_auto_20210120_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buddyrequest',
            name='intensity',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='buddyrequest',
            name='location',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='buddyrequest',
            name='major',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='buddyrequest',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='buddyrequest',
            name='netID',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='buddyrequest',
            name='rescollege',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='buddyrequest',
            name='time_zone',
            field=models.CharField(default='EST', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='buddyrequest',
            name='workout_type',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='buddyrequest',
            name='year',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
