# Generated by Django 3.0.7 on 2020-08-14 21:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuddyRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('netID', models.CharField(default='anonymous_user', max_length=50)),
                ('name', models.CharField(max_length=50, null=True)),
                ('major', models.CharField(max_length=50, null=True)),
                ('year', models.CharField(max_length=50, null=True)),
                ('rescollege', models.CharField(max_length=50, null=True)),
                ('profile_picture', models.ImageField(default='default_profile_picture.png', upload_to='images/')),
                ('days', models.CharField(max_length=300, null=True)),
                ('duration', models.CharField(max_length=50, null=True)),
                ('workout_type', models.CharField(max_length=50, null=True)),
                ('time_zone', models.CharField(max_length=50, null=True)),
                ('partner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
