# Generated by Django 3.0.7 on 2020-07-21 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddyrequest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buddyrequest',
            name='netID',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
