# Generated by Django 3.0.7 on 2020-08-14 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddyrequest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buddyrequest',
            name='netID',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='buddyrequest',
            name='profile_picture',
            field=models.ImageField(default='default_profile_picture.png', null=True, upload_to='images/'),
        ),
    ]
