# Generated by Django 3.0.7 on 2020-07-23 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddyrequest', '0002_buddyrequest_netid'),
    ]

    operations = [
        migrations.AddField(
            model_name='buddyrequest',
            name='profile_picture',
            field=models.ImageField(default='default_profile_picture.png', upload_to='images/'),
        ),
    ]
