# Generated by Django 3.0.7 on 2020-07-25 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buddyrequest', '0003_buddyrequest_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buddyrequest',
            name='group_size',
        ),
    ]
